package com.sdc.core;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Correctness suite for the SDC round-trip pipeline.
 *
 * <h2>Legacy test</h2>
 * <p>{@link #writeAndReadSdc()} exercises the legacy {@link SdcFileWriter}/{@link SdcFileReader}
 * API to guard regression.</p>
 *
 * <h2>Round-trip suite — TASK-012</h2>
 * <p>Iterates over every valid synthetic fixture generated by
 * {@code SegyFixtureGenerator} (in {@code sdc-fixtures}), available on the
 * test classpath via the {@code sdc-fixtures:tests} Maven dependency:</p>
 * <ul>
 *   <li>{@code /fixtures/minimal.segy} — 1 trace, format code 5 (IEEE float32), 100 samples/trace</li>
 *   <li>{@code /fixtures/medium.segy} — 100 traces, format code 5, 500 samples/trace</li>
 *   <li>{@code /fixtures/large.segy} — 200 traces, format code 5, 500 samples/trace</li>
 * </ul>
 *
 * <p>For each fixture the test verifies:</p>
 * <ol>
 *   <li>The fixture bytes are intact before encoding (SHA-256 matches {@code checksums.sha256}).</li>
 *   <li>The pipeline completes without error: encode to {@code .sdc} + decode back to SEG-Y.</li>
 *   <li>The decoded file has the <strong>same size</strong> as the original fixture.</li>
 *   <li>The SEG-Y structural headers (EBCDIC, binary, all trace headers) are
 *       <strong>bit-for-bit identical</strong> to the original.</li>
 *   <li>The round-trip is <strong>deterministic</strong>: two independent encode→decode
 *       executions over the same input produce identical output (SHA-256 matches).</li>
 * </ol>
 *
 * <h3>Note on sample quantisation</h3>
 * <p>The codec pipeline applies 16-bit linear quantisation on trace samples. For
 * SEG-Y format code 5 (IEEE float32), samples with continuous variation (e.g.
 * synthetic sine-wave data) may differ by the quantisation epsilon after decode.
 * The pipeline is therefore <em>not</em> byte-exact on arbitrary float data, but it
 * is <strong>deterministic</strong> and <strong>header-preserving</strong>. Tests 3–5
 * above verify these guarantees. Test 1 additionally verifies fixture integrity.</p>
 *
 * <p>Corrupted fixtures ({@code corrupt_*.segy}) are explicitly excluded: they are
 * intentionally malformed and are tested separately by {@code SegyValidatorTest}.</p>
 *
 * <p><b>Requirement covered:</b> CA-01 — round-trip pipeline is deterministic,
 * header-preserving and size-stable for format code 5 across all valid synthetic
 * fixtures.</p>
 */
public class SdcRoundTripTest {

    /** SEG-Y structural header sizes (bytes). */
    private static final int EBCDIC_HEADER_SIZE  = 3200;
    private static final int BINARY_HEADER_SIZE  = 400;
    private static final int TRACE_HEADER_SIZE   = 240;

    /** Offset of samplesPerTrace in the binary header (0-based). */
    private static final int BIN_SAMPLES_PER_TRACE_OFFSET = 20;

    // -----------------------------------------------------------------------
    // Legacy test — guards regression of SdcFileWriter / SdcFileReader
    // -----------------------------------------------------------------------

    @Test
    void writeAndReadSdc() throws Exception {
        float[] s1 = {1f,2f,3f};
        float[] s2 = {4f,5f,6f};
        TraceBlock t1 = new TraceBlock(10, s1);
        TraceBlock t2 = new TraceBlock(11, s2);

        Path tmp = Files.createTempFile("test", ".sdc");
        SdcFileWriter.write(tmp, List.of(t1, t2));

        SdcHeader header = SdcFileReader.readHeader(tmp);
        assertEquals(2, header.traceCount());
        assertEquals(3, header.samplesPerTrace());

        var traces = SdcFileReader.readAll(tmp);
        assertEquals(2, traces.size());
        assertEquals(10, traces.get(0).traceId());
        assertEquals(11, traces.get(1).traceId());
    }

    // -----------------------------------------------------------------------
    // TASK-012: sanity check — classpath resources must be accessible
    // -----------------------------------------------------------------------

    /**
     * Verifies that the fixture classpath resources are accessible from the
     * sdc-core test classpath (requires sdc-fixtures:tests dependency to be
     * installed: {@code mvn install -pl sdc-fixtures}).
     */
    @Test
    void fixtureClasspathResourcesAreAccessible() {
        for (String name : List.of("minimal.segy", "medium.segy", "large.segy",
                "corrupt_ebcdic.segy", "corrupt_binary.segy", "corrupt_mid_file.segy",
                "checksums.sha256")) {
            URL url = getClass().getResource("/fixtures/" + name);
            assertNotNull(url,
                    "Expected fixture resource not found on classpath: /fixtures/" + name
                    + ". Ensure sdc-fixtures test-jar is installed: "
                    + "mvn test -pl sdc-fixtures && mvn install -pl sdc-fixtures");
        }
    }

    // -----------------------------------------------------------------------
    // TASK-012: fixture integrity — verify fixtures are intact before encode
    // -----------------------------------------------------------------------

    /**
     * Verifies that each valid fixture loaded from the classpath matches its
     * SHA-256 checksum from {@code /fixtures/checksums.sha256}.
     *
     * <p>This guards against test-jar staleness: if the fixture on the classpath
     * differs from what was generated by {@code SegyFixtureGenerator}, the
     * round-trip test would be testing the wrong data.</p>
     */
    @ParameterizedTest(name = "fixtureIntegrity({0})")
    @ValueSource(strings = {"minimal.segy", "medium.segy", "large.segy"})
    void fixtureIntegrityMatchesChecksums(String fixtureName) throws Exception {
        byte[] segyBytes = loadClasspathResource("/fixtures/" + fixtureName);
        assertNotNull(segyBytes, "Fixture not found on classpath: /fixtures/" + fixtureName);

        String expectedHash = loadExpectedChecksum(fixtureName);
        assertNotNull(expectedHash,
                "No checksum entry for " + fixtureName + " in /fixtures/checksums.sha256");

        String actualHash = sha256Hex(segyBytes);
        assertEquals(expectedHash, actualHash,
                "Fixture " + fixtureName + " on classpath does not match its expected SHA-256. "
                + "Re-run: mvn test -pl sdc-fixtures && mvn install -pl sdc-fixtures");
    }

    // -----------------------------------------------------------------------
    // TASK-012: round-trip correctness — structural header preservation
    // -----------------------------------------------------------------------

    /**
     * Verifies that the SEG-Y structural headers (EBCDIC, binary, all trace
     * headers) are <strong>bit-for-bit identical</strong> after encode → decode.
     *
     * <p>Header preservation is a hard requirement: the codec must copy headers
     * verbatim into the {@code SdcContainerV1} and restore them unchanged during
     * decompression, regardless of the sample data processing.</p>
     */
    @ParameterizedTest(name = "headerPreservation({0})")
    @ValueSource(strings = {"minimal.segy", "medium.segy", "large.segy"})
    void roundTripPreservesHeaders(String fixtureName) throws Exception {
        byte[] originalBytes = loadClasspathResource("/fixtures/" + fixtureName);
        assertNotNull(originalBytes);

        Path tmpSegy = Files.createTempFile("sdc-hdr-" + fixtureName + "-", ".segy");
        Path tmpSdc  = Files.createTempFile("sdc-hdr-" + fixtureName + "-", ".sdc");
        Path tmpOut  = Files.createTempFile("sdc-hdr-" + fixtureName + "-out-", ".segy");

        try {
            Files.write(tmpSegy, originalBytes);

            SegyCompression.compressSegyToSdc(tmpSegy, tmpSdc,
                    CompressionProfile.defaultHighQuality(),
                    TracePredictor.identity(), UUID.randomUUID());

            SegyCompression.decompressSdcToSegy(tmpSdc, tmpOut, TracePredictor.identity());

            byte[] decodedBytes = Files.readAllBytes(tmpOut);

            // Same file size
            assertEquals(originalBytes.length, decodedBytes.length,
                    "File size must be preserved for " + fixtureName);

            // EBCDIC header: bytes 0..3199 must be identical
            assertRegionIdentical(originalBytes, decodedBytes, 0, EBCDIC_HEADER_SIZE,
                    "EBCDIC header", fixtureName);

            // Binary header: bytes 3200..3599 must be identical
            assertRegionIdentical(originalBytes, decodedBytes, EBCDIC_HEADER_SIZE, BINARY_HEADER_SIZE,
                    "binary header", fixtureName);

            // Trace headers: read samplesPerTrace from binary header to compute offsets
            int samplesPerTrace = readUnsignedShortBE(originalBytes,
                    EBCDIC_HEADER_SIZE + BIN_SAMPLES_PER_TRACE_OFFSET);
            int traceDataBytes = samplesPerTrace * 4; // IEEE float32 = 4 bytes/sample
            int traceSize = TRACE_HEADER_SIZE + traceDataBytes;
            int fileHeaderBytes = EBCDIC_HEADER_SIZE + BINARY_HEADER_SIZE;
            int traceCount = (originalBytes.length - fileHeaderBytes) / traceSize;

            for (int t = 0; t < traceCount; t++) {
                int traceOffset = fileHeaderBytes + t * traceSize;
                assertRegionIdentical(originalBytes, decodedBytes, traceOffset, TRACE_HEADER_SIZE,
                        "trace header #" + t, fixtureName);
            }

        } finally {
            deleteSilently(tmpSegy);
            deleteSilently(tmpSdc);
            deleteSilently(tmpOut);
        }
    }

    // -----------------------------------------------------------------------
    // TASK-012: round-trip correctness — pipeline determinism
    // -----------------------------------------------------------------------

    /**
     * Verifies that the encode → decode pipeline is <strong>deterministic</strong>:
     * two independent executions over the same input produce byte-identical output.
     *
     * <p>This is the key correctness guarantee for format code 5: given the same
     * SEG-Y bytes, the pipeline always produces the same decoded bytes. Any
     * non-determinism (e.g. random UUIDs in the container header, non-reproducible
     * floating-point operations) would be caught here.</p>
     *
     * <p>The UUID passed to each encode call is fixed to exclude it as a source
     * of non-determinism — the UUID is metadata only and does not affect decoded
     * sample values.</p>
     */
    @ParameterizedTest(name = "roundTripDeterminism({0})")
    @ValueSource(strings = {"minimal.segy", "medium.segy", "large.segy"})
    void roundTripIsDeterministic(String fixtureName) throws Exception {
        byte[] originalBytes = loadClasspathResource("/fixtures/" + fixtureName);
        assertNotNull(originalBytes);

        UUID fixedUuid = UUID.fromString("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee");

        Path tmpSegy  = Files.createTempFile("sdc-det-" + fixtureName + "-", ".segy");
        Path tmpSdc1  = Files.createTempFile("sdc-det-" + fixtureName + "-r1-", ".sdc");
        Path tmpOut1  = Files.createTempFile("sdc-det-" + fixtureName + "-r1-out-", ".segy");
        Path tmpSdc2  = Files.createTempFile("sdc-det-" + fixtureName + "-r2-", ".sdc");
        Path tmpOut2  = Files.createTempFile("sdc-det-" + fixtureName + "-r2-out-", ".segy");

        try {
            Files.write(tmpSegy, originalBytes);

            // First round-trip
            SegyCompression.compressSegyToSdc(tmpSegy, tmpSdc1,
                    CompressionProfile.defaultHighQuality(),
                    TracePredictor.identity(), fixedUuid);
            SegyCompression.decompressSdcToSegy(tmpSdc1, tmpOut1, TracePredictor.identity());

            // Second round-trip — independent execution, same input
            SegyCompression.compressSegyToSdc(tmpSegy, tmpSdc2,
                    CompressionProfile.defaultHighQuality(),
                    TracePredictor.identity(), fixedUuid);
            SegyCompression.decompressSdcToSegy(tmpSdc2, tmpOut2, TracePredictor.identity());

            byte[] decoded1 = Files.readAllBytes(tmpOut1);
            byte[] decoded2 = Files.readAllBytes(tmpOut2);

            // Both decoded outputs must be identical
            assertEquals(decoded1.length, decoded2.length,
                    "Both round-trips must produce files of equal size for " + fixtureName);

            String hash1 = sha256Hex(decoded1);
            String hash2 = sha256Hex(decoded2);

            assertEquals(hash1, hash2,
                    "Round-trip pipeline must be deterministic for " + fixtureName
                    + "\n  run 1 SHA-256: " + hash1
                    + "\n  run 2 SHA-256: " + hash2);

        } finally {
            deleteSilently(tmpSegy);
            deleteSilently(tmpSdc1);
            deleteSilently(tmpOut1);
            deleteSilently(tmpSdc2);
            deleteSilently(tmpOut2);
        }
    }

    // -----------------------------------------------------------------------
    // TASK-012: round-trip correctness — SDC container validity after encode
    // -----------------------------------------------------------------------

    /**
     * Verifies that the {@code .sdc} container produced by encoding each fixture
     * can be read back as a valid {@link SdcContainerV1} with correct metadata.
     */
    @ParameterizedTest(name = "sdcContainerValid({0})")
    @ValueSource(strings = {"minimal.segy", "medium.segy", "large.segy"})
    void encodedContainerHasValidMetadata(String fixtureName) throws Exception {
        byte[] originalBytes = loadClasspathResource("/fixtures/" + fixtureName);
        assertNotNull(originalBytes);

        // Read samplesPerTrace and traceCount from the original fixture
        int samplesPerTrace = readUnsignedShortBE(originalBytes,
                EBCDIC_HEADER_SIZE + BIN_SAMPLES_PER_TRACE_OFFSET);
        int fileHeaderBytes = EBCDIC_HEADER_SIZE + BINARY_HEADER_SIZE;
        int traceSize = TRACE_HEADER_SIZE + samplesPerTrace * 4;
        int traceCount = (originalBytes.length - fileHeaderBytes) / traceSize;

        UUID expectedUuid = UUID.fromString("12345678-abcd-1234-abcd-123456789abc");

        Path tmpSegy = Files.createTempFile("sdc-meta-" + fixtureName + "-", ".segy");
        Path tmpSdc  = Files.createTempFile("sdc-meta-" + fixtureName + "-", ".sdc");

        try {
            Files.write(tmpSegy, originalBytes);

            SegyCompression.compressSegyToSdc(tmpSegy, tmpSdc,
                    CompressionProfile.defaultHighQuality(),
                    TracePredictor.identity(), expectedUuid);

            // Read the container and verify metadata
            SdcContainerV1 container;
            try (var in = new java.io.BufferedInputStream(Files.newInputStream(tmpSdc))) {
                container = SdcContainerV1.read(in);
            }

            assertEquals(expectedUuid, container.modelUuid(),
                    "UUID must be preserved in container for " + fixtureName);
            assertEquals(traceCount, container.traceCount(),
                    "traceCount must match fixture for " + fixtureName);
            assertEquals(samplesPerTrace, container.samplesPerTrace(),
                    "samplesPerTrace must match fixture for " + fixtureName);
            assertEquals(5, container.sampleFormatCode(),
                    "sampleFormatCode must be 5 (IEEE float32) for " + fixtureName);
            assertEquals((short) 1, container.codecVersion(),
                    "codecVersion must be 1 for " + fixtureName);

        } finally {
            deleteSilently(tmpSegy);
            deleteSilently(tmpSdc);
        }
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /**
     * Reads all bytes of a classpath resource. Returns {@code null} if not found.
     */
    private byte[] loadClasspathResource(String path) throws IOException {
        try (InputStream is = getClass().getResourceAsStream(path)) {
            if (is == null) return null;
            return is.readAllBytes();
        }
    }

    /**
     * Parses {@code /fixtures/checksums.sha256} and returns the hex SHA-256 for
     * {@code fixtureName}, or {@code null} if not found.
     *
     * <p>File format (one entry per line): {@code <hex-sha256>  <filename>}</p>
     */
    private String loadExpectedChecksum(String fixtureName) throws IOException {
        byte[] raw = loadClasspathResource("/fixtures/checksums.sha256");
        if (raw == null) {
            fail("/fixtures/checksums.sha256 not found on classpath. "
                    + "Run: mvn test -pl sdc-fixtures && mvn install -pl sdc-fixtures");
        }
        String content = new String(raw, java.nio.charset.StandardCharsets.UTF_8);
        for (String line : content.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty()) continue;
            // format: "<hash>  <filename>" (two spaces, sha256sum convention)
            int sepIdx = trimmed.indexOf("  ");
            if (sepIdx < 0) continue;
            String hash = trimmed.substring(0, sepIdx).trim();
            String name = trimmed.substring(sepIdx + 2).trim();
            if (fixtureName.equals(name)) {
                return hash;
            }
        }
        return null;
    }

    /**
     * Asserts that a region of {@code expected} and {@code actual} byte arrays
     * is bit-for-bit identical.
     */
    private static void assertRegionIdentical(byte[] expected, byte[] actual,
                                               int offset, int length,
                                               String regionName, String fixtureName) {
        for (int i = 0; i < length; i++) {
            int absOffset = offset + i;
            if (absOffset >= expected.length || absOffset >= actual.length) break;
            if (expected[absOffset] != actual[absOffset]) {
                fail(regionName + " differs at byte offset " + absOffset
                        + " in fixture " + fixtureName
                        + ": expected 0x" + String.format("%02X", expected[absOffset] & 0xFF)
                        + " but was 0x" + String.format("%02X", actual[absOffset] & 0xFF));
            }
        }
    }

    /**
     * Reads an unsigned 16-bit big-endian value from {@code buf} at {@code offset}.
     */
    private static int readUnsignedShortBE(byte[] buf, int offset) {
        return ((buf[offset] & 0xFF) << 8) | (buf[offset + 1] & 0xFF);
    }

    /**
     * Computes the SHA-256 hex digest of {@code data}.
     */
    private static String sha256Hex(byte[] data) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(md.digest(data));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 not available", e);
        }
    }

    /** Deletes a path silently, ignoring any I/O error. */
    private static void deleteSilently(Path p) {
        try {
            Files.deleteIfExists(p);
        } catch (IOException ignored) {
            // best-effort cleanup
        }
    }
}
